"""
Writes docs/sample_insights.md from the warehouse and the validation outputs.

The hand-written version quoted a regression that understated the temperature effect, a forecast accuracy figure
that was never measured, and geospatial "findings" that a permutation test shows are indistinguishable from chance.
Generating the document from the evaluation outputs keeps the claims tied to evidence.

Run (after the eval_* scripts):
    python python/write_sample_insights.py
"""
import json

import duckdb
import pandas as pd

from common import BASE, DB_PATH, OUT_DIR


def main():
    con = duckdb.connect(str(DB_PATH), read_only=True)
    head = con.execute("""
        select count(*) sessions, count(distinct station_id) stations, count(distinct city_key) cities,
               sum(energy_kwh) kwh, sum(cost_eur) revenue
        from main_marts.fct_charging_sessions""").df().iloc[0]
    util = con.execute("""
        select city_name, avg(utilization_rate) u from main_analytics.station_utilization
        group by 1 order by 2 desc""").df()
    con.close()

    dm = json.loads((OUT_DIR / "demand_model_validation.json").read_text())
    geo = json.loads((OUT_DIR / "geospatial_stress_test.json").read_text())
    bt = pd.read_csv(OUT_DIR / "forecast_backtest_detail.csv")
    wape = (bt.groupby("model")["abs_err"].sum() / bt.groupby("model")["actual_sum"].sum()).sort_values()
    mase = bt.groupby("model")["mase"].mean()

    rec = {r["label"]: r for r in dm["recovery"]}
    cold, wk, cong = rec["cold hinge (per degree below 10 C)"], rec["weekend"], rec["congestion (per index point)"]
    import numpy as np
    pct = lambda x: f"{np.expm1(x):+.1%}"

    md = f"""# Sample Insights (generated output)

_Generated by `python/write_sample_insights.py` from the warehouse and the validation outputs. Data is synthetic except
daily weather (Open-Meteo); see the README's data-provenance section._

## Headline metrics

- **{int(head.sessions):,}** clean charging sessions across **{int(head.stations)}** stations in **{int(head.cities)}** European cities.
- **{head.kwh:,.0f} kWh** delivered and **EUR {head.revenue:,.0f}** session revenue over the 2-year window.
- Mean station utilization by city ranges **{util.u.min():.2%} to {util.u.max():.2%}** ({util.iloc[0].city_name} highest, {util.iloc[-1].city_name} lowest).

## What drives daily charging demand

Full validation: [outputs/demand_model_validation.md](../outputs/demand_model_validation.md).

A pooled OLS (the first version of this analysis) put temperature at only {dm['ols_temp_pct_per_degree']:+.1%} of mean sessions per degree, which looked
significant but badly understated the real effect, because it averaged the cold-weather effect with no effect on warm days. The corrected model is a
Poisson GLM with city fixed effects, a cold-degrees hinge, and robust standard errors:

| Driver | True effect (generator) | Estimated | 95% CI | Truth inside CI |
|---|---:|---:|---|:---:|
| Weekend | {pct(wk['truth'])} | {pct(wk['estimate'])} | [{pct(wk['lo'])}, {pct(wk['hi'])}] | {'yes' if wk['inside'] else 'no'} |
| Each degree below 10 C | {pct(cold['truth'])} | {pct(cold['estimate'])} | [{pct(cold['lo'])}, {pct(cold['hi'])}] | {'yes' if cold['inside'] else 'no'} |
| Each congestion index point | {pct(cong['truth'])} | {pct(cong['estimate'])} | [{pct(cong['lo'])}, {pct(cong['hi'])}] | {'yes' if cong['inside'] else 'no'} |

The true values are known because the generator builds them in, so this checks the *method*, not real EV demand. Congestion and the weekend flag are correlated
({dm['corr_congestion_weekend']:.2f}) because the generator lightens weekend traffic, so in real data those two effects would be hard to separate.

## 30-day demand forecast: measured accuracy

Rolling-origin backtest (8 cities, 12 origins each, 30-day horizon): [outputs/forecast_backtest.md](../outputs/forecast_backtest.md).

| Model | WAPE | MASE |
|---|---:|---:|
""" + "\n".join(f"| {m} | {w:.1%} | {mase[m]:.2f} |" for m, w in wape.items()) + f"""

Day-level error is about {wape['holt_winters']:.0%} because each city sees only about {dm['mean_sessions']:.0f} sessions a day, so Poisson noise dominates.
Holt-Winters beats the seasonal-naive baseline (MASE {mase['holt_winters']:.2f} vs {mase['seasonal_naive']:.2f}) but only modestly beats a flat 28-day mean.
An earlier version of this document claimed forecasts were "within 5-8%" of actuals; that compared 30-day averages, not daily forecasts, and is withdrawn.

## Geospatial: what the expansion analysis can and cannot say

Stress test: [outputs/geospatial_stress_test.md](../outputs/geospatial_stress_test.md).

The analysis flags {geo['observed']} cluster centroids more than 3 km from the nearest station. Shuffling station demand 200 times gives {geo['null_mean']:.1f} flagged on average
(5th-95th percentile {geo['null_p5']:.0f}-{geo['null_p95']:.0f}); permutation p = {geo['p_value']:.2f}. The flags are therefore a property of the station layout, not of demand.
In this data, session volume depends on a station's power and connector count, not its location. Treat the map as a method demonstration.

## Data quality

`outputs/data_quality_report.md` logs every cleaning fix (duplicates, mixed timestamp formats, sign-error costs, imputed energy readings).
"""
    (BASE / "docs" / "sample_insights.md").write_text(md, encoding="utf-8")
    print("Wrote docs/sample_insights.md")


if __name__ == "__main__":
    main()
